### ISSUE TITLE
Running MCCH.jar produces 'Error initializing QuantumRenderer: no suitable pipeline found.'

### ISSUE THREAD

**Issue by SunkenPotato** [vincent64/minecraft-chat-history#2]
I'm running Java 21.0.1.
When I run MCCH.jar in cmd since the launcher didn't work, I get the following stack trace followed by a shutdown:
`WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2b75cc64'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:268)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:280)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by vincent64** [comment]
Hey, thanks for reporting the issue! I'll try to fix this.
Quick question: what OS are you using? Windows? Mac?

**Comment by SunkenPotato** [comment]
I'm using Windows 11 23H2.

**Comment by SzKristof97** [comment]
Same error occured with me.

**OS**: Windows 11 23H2.
**Java Version**: 
  java 22.0.1 2024-04-16
  Java(TM) SE Runtime Environment (build 22.0.1+8-16)
  Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
  
Any update on the problem?

**Comment by vincent64** [comment]
Thanks @SzKristof97 for reporting the issue too! As for updates, I was in vacation and haven't been able to fix the issue yet. The last update of MCCH fixed this issues on some computers, and I haven't been able to replicate the issue on my Win11 laptop, so it'll take a bit of time until I find the cause and publish an update :(

**Comment by SzKristof97** [comment]
Can i ask which java version you are using?

It is possible that the different Java version has packages or deprecated methods that are not in the newer versions.

**Comment by vincent64** [comment]
I used (and tested) Java 8, Java 17, Java 19 and Java 21. However I don't think the problem comes from Java itself, but from JavaFX.
